### PR TITLE
fix: add index signature to PublicEndpoints

### LINKED ISSUE #173: PublicEndpoints doesn't extend gas-client FunctionMap generic properly.
```sh
Type 'PublicEndpoints' does not satisfy the constraint 'FunctionMap'.
  Index signature for type 'string' is missing in type 'PublicEndpoints'.ts(2344)
```

### PR DESCRIPTION
**Pull request by jpoehnelt**
Add an index signature to `PublicEndpoints` interface to match `FunctionMap` in gas-client.

closes #173

### CODE REVIEW

File: src/__fixtures__/class-return-type.d.ts [hunk 1]
```diff
@@ -4,6 +4,7 @@ declare namespace google {
      */
     namespace script {
         interface PublicEndpoints {
+            [key: string]: (...args: unknown[])=>unknown;
```
Comment (fossamagna) [inline src/__fixtures__/class-return-type.d.ts:7]:
```suggestion
            [key: string]: (...args: any[])=>any;
```

File: src/__fixtures__/interface-parameters-public-endpoints.d.ts [hunk 2]
```diff
@@ -4,6 +4,7 @@ declare namespace google {
      */
     namespace script {
         interface PublicEndpoints {
+            [key: string]: (...args: unknown[])=>unknown;
```
Comment (fossamagna) [inline src/__fixtures__/interface-parameters-public-endpoints.d.ts:7]:
```suggestion
            [key: string]: (...args: any[])=>any;
```

File: src/__fixtures__/object-return-type.d.ts [hunk 3]
```diff
@@ -4,6 +4,7 @@ declare namespace google {
      */
     namespace script {
         interface PublicEndpoints {
+            [key: string]: (...args: unknown[])=>unknown;
```
Comment (fossamagna) [inline src/__fixtures__/object-return-type.d.ts:7]:
```suggestion
            [key: string]: (...args: any[])=>any;
```

File: src/__fixtures__/primitive-return-type.d.ts [hunk 4]
```diff
@@ -4,6 +4,7 @@ declare namespace google {
      */
     namespace script {
         interface PublicEndpoints {
+            [key: string]: (...args: unknown[])=>unknown;
```
Comment (fossamagna) [inline src/__fixtures__/primitive-return-type.d.ts:7]:
```suggestion
            [key: string]: (...args: any[])=>any;
```

**Review by fossamagna — CHANGES_REQUESTED** [review]
@jpoehnelt I found a couple things I think need updating, but otherwise it LGTM. Thank you for your contribution!

File: src/__fixtures__/class-return-type.d.ts (hunk 1 above)
Comment (jpoehnelt) [reply src/__fixtures__/class-return-type.d.ts:7]: Why change to `any`? 

`unknown` works and isn't going to cause issues with strict linters

https://www.typescriptlang.org/play?#code/C4TwDgpgBAYgrgOwMbAJYHsEFkCGYoC8UA3gFBQVQDaAHgFxQDOwATqggOYC6DAFAHSCcLDowY4EIKlwCUhAHxQJIANykAvqVLtgEFgDMcSaAAU4AIwA2qJAFEEAEzDodjEuUpUA1hBANmbJw8UAJCImJQiF4I6ADuCNJyBIpRMfEaWkiWOIxuAOIAggDKAMLWEAjAADwAKlAQNLqObvDIaJi4+ETE6oo9WggQsVCFpeWVVWZWNvZOLpWM8rwyQA

Comment (jpoehnelt) [reply src/__fixtures__/class-return-type.d.ts:7]: dts-dom doesn't currently support `unknown`. will update

**Comment by jpoehnelt** [comment]
`unknown` is blocked by https://github.com/RyanCavanaugh/dts-dom/pull/86

**Review by fossamagna — APPROVED** [review]
